#define IDH_FileFUNCTION_H20 10
#define IDH_Blocchidiriferimentodegliattributivisibili 11
#define IDH_Attributipredefinitiperleclassidientitsimulazione 12
#define IDH_Attributinodo 13
#define IDH_Attributiserbatoio 14
#define IDH_Attributiregolatore 15
#define IDH_Attributipompa 16
#define IDH_Attributivalvola 17
#define IDH_Attributivalvolaregolatricedipressione 18
#define IDH_Attributilato 19
#define IDH_INFORMAZIONISUGEOSIMPRESSURENETWORK 1
#define IDH_Descrizionedelfilepompe_ini 20
#define IDH_Tabellediriferimentopredefinitepergliattributi 21
#define IDH_Operazioniinerentileclassidientitsimulazione 22
#define IDH_GESTIONESESSIONIDILAVORO 23
#define IDH_Inserimentoentitsimulazione 25
#define IDH_ApplicazionedeicomandiinGEOsimPressureNetwork 26
#define IDH_SIMULAZIONERETIINPRESSIONE 27
#define IDH_Simulazionereteacqua 29
#define IDH_Simulazioneretegas 30
#define IDH_Esempioapplicativo 31
#define IDH_Stampadeidatidiinputoutput 32
#define IDH_PROGETTAZIONEDELLERETIACQUAEGAS 33
#define IDH_Calcolodeidiametri 35
#define IDH_Gestionedeidiametricommerciali 36
#define IDH_VERIFICACONNESSIONI 37
#define IDH_Verificaconnessioneconsiderandolostatodellevalvole 39
#define IDH_Notesullaprogettazioneeverificadelleretiinpressione 3
#define IDH_Verificaconnessioniperflusso 40
#define IDH_ISOPIEZE 41
#define IDH_VERIFICAVALVOLEPERISOLARELARETE 43
#define IDH_RICERCASOTTORETI 45
#define IDH_Elencodellesottoreti 47
#define IDH_STUDIODELLAQUALITADELLACQUA 48
#define IDH_Formuledicalcolodelleperditedicarico 4
#define IDH_Analisidelletdellacqua 50
#define IDH_Analisidisostanzenonreattive 51
#define IDH_Analisidisostanzereattive 52
#define IDH_Sostanzepresentinellacquapotabile 53
#define IDH_Sostanzeinorganiche 54
#define IDH_Sostanzeorganiche 55
#define IDH_Disinfettanti 56
#define IDH_Sottoprodottideidisinfettanti 57
#define IDH_Modellazionedisostanzenonreattive 58
#define IDH_Modellazionedeinitrati 59
#define IDH_Elementispeciali 5
#define IDH_DurezzaConduttivit 60
#define IDH_Modellazionediunincidenteinquinante 61
#define IDH_Modellazionedeifluoruri 62
#define IDH_Datinecessariallamodellazionedisostanzenonreattive 63
#define IDH_Modellazionedisostanzereattive 64
#define IDH_LosviluppodeitrialometaniTHM 66
#define IDH_Datinecessariallamodellazionedisostanzereattive 67
#define IDH_Perchilclorodecade 68
#define IDH_Datinecessariallamodellazionedelcloro 69
#define IDH_GESTIONEDELLECLASSIDIENTITSIMULAZIONE 6
#define IDH_Dettagliodelmodelloperilcloro 70
#define IDH_Coefficientididecadimento 71
#define IDH_Analisidelletdellacqua10_5_ 72
#define IDH_Visualizzazionedeirisultatidelmodelloperletdellacqua 73
#define IDH_Analisidelleconcentrazionidisostanzenonreattive 74
#define IDH_Visualizzazionedeirisultatidelmodelloperlaconcentrazionedisostanzenon_reattive 75
#define IDH_Analisidelleconcentrazionidisostanzereattive 76
#define IDH_Visualizzazionedeirisultatidelmodelloperlaconcentrazionedisostanzereattive 77
#define IDH_Limitidellamodellazionedisostanzereattive 78
#define IDH_NUOVEFUNZIONALIT 79
#define IDH_Filedisupportoperlagestionedelleclassidientitsimulazione 8
#define IDH_CennisuiFilediStruttura 9
